### ISSUE TITLE
check in modifier (canBeStoredWith128Bits)

### ISSUE THREAD

**Issue by pauliax** [axiomzen/cryptokitties-bounty#11]
The check in this modifier should be "<=" 

    modifier canBeStoredWith128Bits(uint256 _value) {
        require(_value < 340282366920938463463374607431768211455);
        _;
    }

because 128 bits can hold a maximum of 2^128-1 which is equal to 340282366920938463463374607431768211455 so it makes sense (according to the modifier's name) to have a "<=" instead of "<".

by the way, here everything is fine:
    modifier canBeStoredWith64Bits(uint256 _value) {
        require(_value <= 18446744073709551615);
        _;
    }

**Comment by pauliax** [comment]
// sanity check to ensure we don't overflow arithmetic (this big number is 2^128-1).
        require(avePrice < 340282366920938463463374607431768211455);
Same here (KittyMinting.sol)

**Comment by dete** [comment]
Great point! Thanks for reporting it, @pauliax!

Please see #13 for some info on how we're planning to replace these checks, based on a Gitter suggestion from @arachnid.
