### ISSUE TITLE
bid amount: comment vs code

### ISSUE THREAD

**Issue by pauliax** [axiomzen/cryptokitties-bounty#12]
// Check that the incoming bid is higher than the current
        // price
        uint256 price = _currentPrice(auction);
        require(_bidAmount >= price);

The comment says that the bid should be higher, however, the code also allows equal value, so please either refactor the code or update the comment.

**Comment by kimcope** [comment]
Thanks for your participation, @pauliax!

**Comment by Dman89** [comment]
That is a huge bug...
