### ISSUE TITLE
Hardcoded numbers

### ISSUE THREAD

**Issue by pauliax** [axiomzen/cryptokitties-bounty#13]
require(_matronId <= 4294967295);
        require(_sireId <= 4294967295);
        require(_generation <= 65535);

 // ... some other code...

        require(newKittenId <= 4294967295);

It's generally advised to avoid hardcoded numbers in functions. Functions shouldn't have magic numbers inside it. It makes harder to maintain the code and also decreases readability. Imagine if you use a magic number, let's say 350 ten times in your code. One day you decide to change it from 350 to 360. What do you do? You search all occurrences in the code and change them. If you have this value extracted, you can change it only in one place to achieve the same effect.

**Comment by dete** [comment]
> Functions shouldn't have magic numbers inside it.

I totally agree, but – believe it or not! – we didn't realize until recently that Solidity efficiently supported named constants. (See #6.)

We're actually planning on replacing these checks with a technique @arachnid suggested in the Gitter chat ([link](https://gitter.im/Crypto_Kitties/Lobby?at=5a0db5bc982ea2653f8940ea)).
