### ISSUE TITLE
Limit gasPrice in auctions

### ISSUE THREAD

**Issue by 3esmit** [axiomzen/cryptokitties-bounty#23]
### Description
People are using very high gas price to get advantage in auctions, and leading everyone to also have to rise their gasPrices.

### Impact
Network congestion

### Fix
Require a limit to gasPrice of 5 gwei in auctions modifieres or equivalent.

**Comment by flockonus** [comment]
The fact that ppl were or are sending higher gas price is an Ethereum hard characteristic, for the contract is completely unknown how much gas price was set in the transaction.

Also what causes network congestion is the sheer amount of users sending txs. versus what the network can support, the rising gas price is expected for Ethereum
