### ISSUE TITLE
setCEO error

### ISSUE THREAD

**Issue by brewswang** [axiomzen/cryptokitties-bounty#25]
await testInstance.setCEO("0x200611411221535804aa6f053c5fcc78ef1354d5");
Error: invalid address   throw new Error('invalid address');

accounts: 
Array [ "0x9556d2d19f5195454bf6034221bb20477f716bc5", "0xd75ccf594ed62dff1771635d310d02f013384c6b", "0xe77603a978adb27ac4a282edc4fcb0443847d24e", "0x3ba1d1bfc848c5174713710a0f94305f93922e6f", "0x922aacf435e4d9c767b7b0360e5ab702b4884b6f", "0x615345b4d999942a7ee30b54b72ee83fe82a62a5", "0xfa9e19079b0e90e36e5410bca6d1d5b39cbb4779", "0x870d0e5a84cb8120ef99a391c9430ede6496db1f", "0xf24eeec90b57da68325e9750a0972113c4ef1100", "0x200611411221535804aa6f053c5fcc78ef1354d5" ]

**Comment by flockonus** [comment]
Can you clarify? Not sure what's the vulnerability or error is coming from
