### ISSUE TITLE
Code is open source

### ISSUE THREAD

**Issue by fulldecent** [axiomzen/cryptokitties-bounty#26]
This comment suggests that CK is open source (except for gene splicing): https://github.com/axiomzen/cryptokitties-bounty/blob/e0d9c2c90964b1bbb242d8e3e0d9a7786cf21182/contracts/KittyCore.sol#L16-L17

But the license file contracts this: https://github.com/axiomzen/cryptokitties-bounty/blob/master/LICENSE.md

So is this code open source or not?

**Comment by flockonus** [comment]
Hey @fulldecent, the LICENSE.md is the actual license and applies to all the code in the repo.
The most recent code is posted to etherscan for user transparency, still, all rights are kept and maintained by AxiomZen
