### ISSUE TITLE
**Recommendation** Adding events to track 'C' level updates

### ISSUE THREAD

**Issue by palanisn** [axiomzen/cryptokitties-bounty#8]
### Description
Updates for 'C' level role changes don't fire events, its a good idea to have this in place to trace all significant events that happen on the contract.

### Reproduction
Invoking a COO / CFO address update action by the CEO does not trigger events.

### Fix
Add events to indicate that the COO / CFO role addresses have been updated.

**Comment by dete** [comment]
Thanks for taking the time to report this, @palanisn.

We talked about it internally and if an unauthorized party can control the CEO address, it's already game over. Building the infrastructure to report and track address updates is like building a special machine just for closing barn doors after all the horses have escaped! 😆 

We appreciate your efforts!

**Comment by fulldecent** [comment]
This is incorrect. 

"Game over" here implies that CryptoKitties would have zero financial incentive to maintain their website and would shut it down, then everybody else would quickly become informed of the situation (no information asymmetry).

Instead, the attack vector is that somebody steals the CEO account, but AxiomZen maintains access to many high-value kitties. In this situation, CryptoKitties and the attacker would both be incentivized to keep information asymmetry from the public until AxiomZen unloads their high value assets.

But of course, anybody could query the public ceo function to get the same information anyway. So this is high-impact but low-likelihood.
