### ISSUE TITLE
Add Checks to ensure 'C' level role addresses are updated with different values

### ISSUE THREAD

**Issue by palanisn** [axiomzen/cryptokitties-bounty#9]
### Description
There is no check available in setCEO / setCFO / setCOO methods to ensure that the incoming address is different from the current address of the respective role. By adding this additional check, any attempt to re-assign the same address value to a particular role can be avoided, saving gas cost.

### Scenario
CEO address is 0x16baf0de678e52367adc69fd067e5edd1d33e00f. CEO invokes with the same address value setCEO("0x16baf0de678e52367adc69fd067e5edd1d33e00f"). This transaction would go through because there is no check to validate if the incoming address is not same as the current address.

Same applies for the setCOO & set CFO methods.

### Impact
No real attack vector but possibility to save some gas.

### Reproduction
Refer Scenario above.

### Fix
Add require statement to ensure that the incoming address is different from the current address.

function setCEO(address _newCEO) public onlyCEO {
        require(_newCEO != ceoAddress);
        require(_newCEO != address(0));

        ceoAddress = _newCEO;
    }

Similar checks can be applied for the setCOO & set CFO methods.

**Comment by dete** [comment]
I love the intensity of your scrutiny here, @palanisn!

As you point out, the only possible impact here is wasting gas on a no-op, but given that these addresses will change very infrequently (if at all) it's not really worth guarding against.

Thanks again for reporting!
